run_modules:
- fastqc
- fastp
- busco
- quast
sp: {}
module_order:

# ONT QC
- fastqc:
    name: FastQC (Raw_FQ)
    path_filters: SHORT_READ_ISOLATE/READ_QC_SR/RAW_FASTQC/*/*_fastqc.zip
- fastp:
    name: FastP
    path_filters: SHORT_READ_ISOLATE/READ_QC_SR/FASTP/*.json 
- fastqc:
    name: FastQC (Final_QC)
    path_filters: SHORT_READ_ISOLATE/READ_QC_SR/TRIM_FASTQC/*/*_fastqc.zip
- busco:
    name: BUSCO
    path_filters: SHORT_READ_ISOLATE/SHORT_READ_ISOLATE_ASSEMBLY/BUSCO_GENOME/*/*_busco.txt
- quast:
    name: Assembly Stats
    path_filters: SHORT_READ_ISOLATE/SHORT_READ_ISOLATE_ASSEMBLY/QUAST_GENOME/*/report.tsv